# Generated by Django 2.0.1 on 2018-02-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characterfgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank_card', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3')], max_length=20)),
                ('type_card', models.CharField(choices=[('servant', 'Servant'), ('craft_essense', 'Craft Essense')], max_length=20)),
                ('image_path', models.CharField(max_length=300)),
            ],
        ),
    ]
